# Generated by Django 5.1.4 on 2024-12-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=30)),
                ("userid", models.DecimalField(decimal_places=0, max_digits=2)),
                ("busid", models.DecimalField(decimal_places=0, max_digits=2)),
                ("bus_name", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=30)),
                ("dest", models.CharField(max_length=30)),
                ("nos", models.DecimalField(decimal_places=0, max_digits=2)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("B", "Booked"), ("C", "Cancelled")],
                        default="B",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List of Books",
            },
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bus_name", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=30)),
                ("dest", models.CharField(max_length=30)),
                ("nos", models.DecimalField(decimal_places=0, max_digits=2)),
                ("rem", models.DecimalField(decimal_places=0, max_digits=2)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "List of Busses",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "List of Users",
            },
        ),
    ]
