# Generated by Django 5.1.4 on 2025-01-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name_plural": "List of Buses"},
        ),
        migrations.AlterField(
            model_name="book",
            name="busid",
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "BOOKED"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="BOOKED",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="userid",
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="bus",
            name="bus_name",
            field=models.CharField(
                choices=[
                    ("TG 76Z 0001 Express", "TG 76Z 0001 Express"),
                    ("TG 76Z 0002 Express", "TG 76Z 0002 Express"),
                    ("TG 76Z 0003 Express", "TG 76Z 0003 Express"),
                    ("TG 76Z 0004 Express", "TG 76Z 0004 Express"),
                    ("TG 76Z 0005 Express", "TG 76Z 0005 Express"),
                    ("TG 76Z 0006 Deluxe", "TG 76Z 0006 Deluxe"),
                    ("TG 76Z 0007 Deluxe", "TG 76Z 0007 Deluxe"),
                    ("TG 76Z 0008 Deluxe", "TG 76Z 0008 Deluxe"),
                    ("TG 76Z 0009 Deluxe", "TG 76Z 0009 Deluxe"),
                    ("TG 76Z 0010 Deluxe", "TG 76Z 0010 Deluxe"),
                    ("TG 76Z 0011 Super Luxury", "TG 76Z 0011 Super Luxury"),
                    ("TG 76Z 0012 Super Luxury", "TG 76Z 0012 Super Luxury"),
                    ("TG 76Z 0013 Super Luxury", "TG 76Z 0013 Super Luxury"),
                    ("TG 76Z 0014 Super Luxury", "TG 76Z 0014 Super Luxury"),
                    ("TG 76Z 0015 Super Luxury", "TG 76Z 0015 Super Luxury"),
                    ("TG 76Z 0016 EV Bus", "TG 76Z 0016 EV Bus"),
                    ("TG 76Z 0017 EV Bus", "TG 76Z 0017 EV Bus"),
                    ("TG 76Z 0018 EV Bus", "TG 76Z 0018 EV Bus"),
                    ("TG 76Z 0019 EV Bus", "TG 76Z 0019 EV Bus"),
                    ("TG 76Z 0020 EV Bus", "TG 76Z 0020 EV Bus"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="dest",
            field=models.CharField(
                choices=[
                    ("Hyderabad", "Hyderabad"),
                    ("Warangal", "Warangal"),
                    ("Nizamabad", "Nizamabad"),
                    ("Khammam", "Khammam"),
                    ("Karimnagar", "Karimnagar"),
                    ("Ramagundam", "Ramagundam"),
                    ("Medak", "Medak"),
                    ("Nalgonda", "Nalgonda"),
                    ("Adilabad", "Adilabad"),
                    ("Suryapet", "Suryapet"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="nos",
            field=models.IntegerField(choices=[(40, "40"), (50, "50"), (60, "60")]),
        ),
        migrations.AlterField(
            model_name="bus",
            name="source",
            field=models.CharField(
                choices=[
                    ("Hyderabad", "Hyderabad"),
                    ("Warangal", "Warangal"),
                    ("Nizamabad", "Nizamabad"),
                    ("Khammam", "Khammam"),
                    ("Karimnagar", "Karimnagar"),
                    ("Ramagundam", "Ramagundam"),
                    ("Medak", "Medak"),
                    ("Nalgonda", "Nalgonda"),
                    ("Adilabad", "Adilabad"),
                    ("Suryapet", "Suryapet"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="time",
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("issue", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Messages",
            },
        ),
    ]
